USE [master]
GO

/****** Object:  Database [OurFirstDB]    Script Date: 2025/03/10 19:57:03 ******/
CREATE DATABASE [OurFirstDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OurFirstDB', FILENAME = N'C:\sc_LuckyManamela_2025\DatabaseAdministration\SQLStatements\OurFirstDB.mdf' , SIZE = 65536KB , MAXSIZE = 1048576KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OurFirstDB_log', FILENAME = N'C:\sc_LuckyManamela_2025\DatabaseAdministration\SQLStatements\OurFirstDB_log.ldf' , SIZE = 32768KB , MAXSIZE = 512000KB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OurFirstDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OurFirstDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OurFirstDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OurFirstDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OurFirstDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OurFirstDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [OurFirstDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OurFirstDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OurFirstDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OurFirstDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OurFirstDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OurFirstDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OurFirstDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OurFirstDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OurFirstDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OurFirstDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OurFirstDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OurFirstDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OurFirstDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OurFirstDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OurFirstDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OurFirstDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OurFirstDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OurFirstDB] SET RECOVERY FULL 
GO

ALTER DATABASE [OurFirstDB] SET  MULTI_USER 
GO

ALTER DATABASE [OurFirstDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OurFirstDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OurFirstDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OurFirstDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [OurFirstDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OurFirstDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [OurFirstDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [OurFirstDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [OurFirstDB] SET  READ_WRITE 
GO


