name: Deploy TimesheetDB and Trigger SSIS Jobs

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/**'
      - 'HandsOnProjects/TimesheetMigration/TimesheetMigration/**'
  workflow_dispatch:

env:
  DATABASE_NAME: TimesheetDB
  SSIS_FOLDER_NAME: TimesheetDataMigration
  SSIS_PROJECT_NAME: Projects/Timesheets/Packages
  SSIS_PACKAGE_NAME: TimeSheetMigration 1.dtsx
  SQL_SERVER_NAME: ${{ secrets.SQL_SERVER_NAME }}
  SQL_USERNAME: ${{ secrets.SQL_USERNAME }}
  SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}

jobs:
  deploy-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SQL Server tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc
        shell: bash

      - name: Execute SQL Script
        run: |
          if ! /opt/mssql-tools/bin/sqlcmd -b -S "${{ env.SQL_SERVER_NAME }}" -U "${{ env.SQL_USERNAME }}" -P "${{ env.SQL_PASSWORD }}" -N -d master -i scripts/TimesheetDB.sql -o output.log; then
            echo "Error: SQL script execution failed. Check output.log for details."
            cat output.log
            exit 1
          fi
          echo "SQL script executed successfully."
          cat output.log
        shell: bash

      - name: Trigger Sub-Main Workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"deploy_ssis"}'
        shell: bash

  setup-and-execute-job:
    runs-on: [self-hosted, windows]
    needs: deploy-database
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SQLCMD
        run: |
          Invoke-WebRequest -Uri "https://github.com/microsoft/go-sqlcmd/releases/download/v1.5.0/sqlcmd-1.5.0-windows-amd64.zip" -OutFile sqlcmd.zip
          Expand-Archive -Path sqlcmd.zip -DestinationPath sqlcmd
          echo "C:\sqlcmd" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: Setup SQL Server Agent Job
        run: |
          echo. > setup_job.sql
          echo USE msdb; >> setup_job.sql
          echo IF NOT EXISTS (SELECT 1 FROM sysjobs WHERE name = 'TimesheetProjectRun') >> setup_job.sql
          echo BEGIN >> setup_job.sql
          echo     EXEC dbo.sp_add_job @job_name = N'TimesheetProjectRun'; >> setup_job.sql
          echo     EXEC sp_add_jobstep >> setup_job.sql
          echo         @job_name = N'TimesheetProjectRun', >> setup_job.sql
          echo         @step_name = N'Run SSIS Package', >> setup_job.sql
          echo         @subsystem = N'SSIS', >> setup_job.sql
          echo         @command = N'/ISSERVER "\${{ env.SSIS_FOLDER_NAME }}\${{ env.SSIS_PROJECT_NAME }}\${{ env.SSIS_PACKAGE_NAME }}" /SERVER "MANAMELA" /Par "$ServerOption::LOGGING_LEVEL(Int16)";1 /Par "$ServerOption::SYNCHRONIZED(Boolean)";True /CALLERINFO SQLAGENT /REPORTING E', >> setup_job.sql
          echo         @database_name = N'master'; >> setup_job.sql
          echo     EXEC dbo.sp_add_jobschedule >> setup_job.sql
          echo         @job_name = N'TimesheetProjectRun', >> setup_job.sql
          echo         @name = N'RunNow', >> setup_job.sql
          echo         @enabled = 1, >> setup_job.sql
          echo         @freq_type = 1, >> setup_job.sql
          echo         @active_start_date = %date:~10,4%%date:~4,2%%date:~7,2%, >> setup_job.sql
          echo         @active_start_time = %time:~0,2%%time:~3,2%%time:~6,2%; >> setup_job.sql
          echo     EXEC dbo.sp_add_jobserver @job_name = N'TimesheetProjectRun'; >> setup_job.sql
          echo END >> setup_job.sql
          echo ELSE >> setup_job.sql
          echo BEGIN >> setup_job.sql
          echo     EXEC sp_update_jobstep >> setup_job.sql
          echo         @job_name = N'TimesheetProjectRun', >> setup_job.sql
          echo         @step_id = 1, >> setup_job.sql
          echo         @command = N'/ISSERVER "\${{ env.SSIS_FOLDER_NAME }}\${{ env.SSIS_PROJECT_NAME }}\${{ env.SSIS_PACKAGE_NAME }}" /SERVER "MANAMELA" /Par "$ServerOption::LOGGING_LEVEL(Int16)";1 /Par "$ServerOption::SYNCHRONIZED(Boolean)";True /CALLERINFO SQLAGENT /REPORTING E'; >> setup_job.sql
          echo END >> setup_job.sql
          if ! sqlcmd -b -S "MANAMELA" -U "${{ env.SQL_USERNAME }}" -P "${{ env.SQL_PASSWORD }}" -i setup_job.sql; then
            echo "Error: Job setup failed."
            exit 1
          fi
          echo "Job setup completed."
        shell: cmd

      - name: Execute SQL Server Agent Job
        run: |
          if ! sqlcmd -b -S "MANAMELA" -U "${{ env.SQL_USERNAME }}" -P "${{ env.SQL_PASSWORD }}" -Q "EXEC msdb.dbo.sp_start_job N'TimesheetProjectRun';"; then
            echo "Error: Job execution failed."
            exit 1
          fi
          echo "Job executed successfully."
        shell: cmd