name: Full Deployment - TimesheetDB + SSIS + SQL Agent Job

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/**'
      - 'HandsOnProjects/TimesheetMigration/TimesheetMigration/**'
  workflow_dispatch:

env:
  SQL_SERVER_NAME: ${{ secrets.SQL_SERVER_NAME }}  # Set to Sambe2025008 or localhost
  SSISDB_PASSWORD: ${{ secrets.SSISDB_PASSWORD }}
  SSIS_DEST_FOLDER: 'NewDataMigration'
  SSIS_PROJECTS_FOLDER: 'TimesheetMigration'
  PACKAGE_NAME: 'TimeSheetMigration 1.dtsx'
  SSIS_SOURCE_PATH: 'HandsOnProjects/TimesheetMigration/TimesheetMigration/bin/Development/TimesheetMigration.ispac'
  JOB_NAME: 'RunDataMigrationPackage'
  SQL_SERVER_LOCAL: 'Sambe2025008'

jobs:
  deploy-database:
    name: Deploy Database Scripts
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SQL Server Tools
        run: |
          choco install sqlserver-odbcdriver -y
          choco install sqlserver-cmdlineutils -y
          $env:Path += ";C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\"
          [Environment]::SetEnvironmentVariable("Path", $env:Path, [System.EnvironmentVariableTarget]::Process)
        shell: powershell

      - name: Test SQL Server Connectivity
        run: |
          ping -n 4 "${{ env.SQL_SERVER_NAME }}"
          Test-NetConnection -ComputerName "${{ env.SQL_SERVER_NAME }}" -Port 1433
        shell: powershell
        env:
          SQL_SERVER_NAME: ${{ secrets.SQL_SERVER_NAME }}

      - name: Run TimesheetDB SQL Script
        run: |
          sqlcmd -S "${{ env.SQL_SERVER_NAME }}" -E -d master -i "$env:GITHUB_WORKSPACE/scripts/TimesheetDB.sql" -b
        shell: powershell
        env:
          SQL_SERVER_NAME: ${{ env.SQL_SERVER_NAME }}
          GITHUB_WORKSPACE: ${{ github.workspace }}

  deploy-ssis:
    name: Deploy SSIS Project and Run Job
    runs-on: [self-hosted, windows]
    needs: deploy-database

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy SSIS Project to SSISDB using Integrated Auth
        shell: powershell
        run: |
          $ispacPath = Join-Path $env:GITHUB_WORKSPACE $env:SSIS_SOURCE_PATH
          if (-not (Test-Path $ispacPath)) {
              throw "ISPAC not found at $ispacPath"
          }

          [byte[]]$bytes = [System.IO.File]::ReadAllBytes($ispacPath)
          $hexString = [System.BitConverter]::ToString($bytes) -replace '-', ''

          $sql = @"
          IF NOT EXISTS (SELECT 1 FROM SSISDB.catalog.folders WHERE name = N'$env:SSIS_DEST_FOLDER')
          BEGIN
              EXEC SSISDB.catalog.create_folder @folder_name = N'$env:SSIS_DEST_FOLDER';
          END

          DECLARE @project_stream VARBINARY(MAX) = CONVERT(VARBINARY(MAX), 0x$hexString, 1);
          EXEC SSISDB.catalog.deploy_project
              @folder_name = N'$env:SSIS_DEST_FOLDER',
              @project_name = N'$env:SSIS_PROJECTS_FOLDER',
              @project_stream = @project_stream;
          "@

          $tempSqlPath = "$env:RUNNER_TEMP\deploy_ssis_project.sql"
          [System.IO.File]::WriteAllText($tempSqlPath, $sql)

          & sqlcmd -S $env:SQL_SERVER_NAME -E -d SSISDB -i $tempSqlPath -b

          if ($LASTEXITCODE -ne 0) {
              throw "SSIS project deployment failed with exit code $LASTEXITCODE"
          }
        env:
          SQL_SERVER_NAME: ${{ env.SQL_SERVER_NAME }}
          SSIS_DEST_FOLDER: ${{ env.SSIS_DEST_FOLDER }}
          SSIS_PROJECTS_FOLDER: ${{ env.SSIS_PROJECTS_FOLDER }}
          SSIS_SOURCE_PATH: ${{ env.SSIS_SOURCE_PATH }}

      - name: Create SQL Agent Job if Missing
        shell: powershell
        run: |
          $packagePath = "/SSISDB/$env:SSIS_DEST_FOLDER/$env:SSIS_PROJECTS_FOLDER/$env:PACKAGE_NAME"
          $command = "/ISSERVER `"$packagePath`" /SERVER `"$env:SQL_SERVER_NAME`""
          $sql = @'
          USE msdb;
          IF NOT EXISTS (SELECT 1 FROM msdb.dbo.sysjobs WHERE name = N'$env:JOB_NAME')
          BEGIN
            DECLARE @jobId UNIQUEIDENTIFIER;
            EXEC msdb.dbo.sp_add_job
              @job_name = N'$env:JOB_NAME',
              @enabled = 1,
              @description = N''Data Migration SSIS Job'',
              @start_step_id = 1,
              @owner_login_name = SUSER_SNAME(),
              @job_id = @jobId OUTPUT;

            EXEC msdb.dbo.sp_add_jobstep
              @job_id = @jobId,
              @step_id = 1,
              @step_name = N''RunMigrationStep'',
              @subsystem = N''SSIS'',
              @command = N''$command'',
              @database_name = N''master'',
              @on_success_action = 1,
              @on_fail_action = 2;

            EXEC msdb.dbo.sp_add_jobserver @job_id = @jobId, @server_name = N''$env:SQL_SERVER_LOCAL'';
          END
          '@ -replace '\$env:JOB_NAME', $env:JOB_NAME -replace '\$env:SQL_SERVER_LOCAL', $env:SQL_SERVER_LOCAL -replace '\$command', $command
          & sqlcmd -S $env:SQL_SERVER_NAME -E -Q $sql -b
        env:
          SQL_SERVER_NAME: ${{ env.SQL_SERVER_NAME }}
          SSIS_DEST_FOLDER: ${{ env.SSIS_DEST_FOLDER }}
          SSIS_PROJECTS_FOLDER: ${{ env.SSIS_PROJECTS_FOLDER }}
          PACKAGE_NAME: ${{ env.PACKAGE_NAME }}
          SSIS_SOURCE_PATH: ${{ env.SSIS_SOURCE_PATH }}
          JOB_NAME: ${{ env.JOB_NAME }}
          SQL_SERVER_LOCAL: ${{ env.SQL_SERVER_LOCAL }}

      - name: Start SQL Agent Job
        shell: powershell
        run: |
          & sqlcmd -S $env:SQL_SERVER_NAME -E -Q "EXEC msdb.dbo.sp_start_job @job_name = N'$env:JOB_NAME';" -b
        env:
          SQL_SERVER_NAME: ${{ env.SQL_SERVER_NAME }}
          JOB_NAME: ${{ env.JOB_NAME }}