name: Full Deployment - TimesheetDB + SSIS + SQL Agent Job

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/**'
      - 'HandsOnProjects/TimesheetMigration/TimesheetMigration/**'
  workflow_dispatch:

env:
  SQL_SERVER_NAME: ${{ secrets.SQL_SERVER_NAME }}
  SQL_USERNAME: ${{ secrets.SQL_USERNAME }}  # LuckyManamela
  SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}  # Password for LuckyManamela
  SSISDB_PASSWORD: ${{ secrets.SSISDB_PASSWORD }}
  SSIS_DEST_FOLDER: 'NewDataMigration'
  SSIS_PROJECTS_FOLDER: 'TimesheetMigration'
  PACKAGE_NAME: 'TimeSheetMigration 1.dtsx'
  SSIS_SOURCE_PATH: 'HandsOnProjects/TimesheetMigration/TimesheetMigration/bin/Development/TimesheetMigration.ispac'
  JOB_NAME: 'RunDataMigrationPackage'
  SQL_SERVER_LOCAL: 'SAMBE2025008'

jobs:
  deploy-database:
    name: Deploy Database Scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SQL Server Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> $GITHUB_ENV

      - name: Run TimesheetDB SQL Script (optional)
        run: |
          /opt/mssql-tools/bin/sqlcmd -S "${{ env.SQL_SERVER_NAME }}" -U "${{ env.SQL_USERNAME }}" -P "${{ env.SQL_PASSWORD }}" -d master -i "$GITHUB_WORKSPACE/scripts/TimesheetDB.sql"
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

  deploy-ssis:
    name: Deploy SSIS Project and Run Job
    runs-on: [self-hosted, windows]
    needs: deploy-database

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy SSIS Project to SSISDB using SQL Auth
        shell: powershell
        run: |
          $ispacPath = Join-Path $env:GITHUB_WORKSPACE $env:SSIS_SOURCE_PATH
          if (-not (Test-Path $ispacPath)) {
              throw "ISPAC not found at $ispacPath"
          }

          [byte[]]$bytes = [System.IO.File]::ReadAllBytes($ispacPath)
          $hexString = [System.BitConverter]::ToString($bytes) -replace '-', ''

          $sql = @"
          IF NOT EXISTS (SELECT 1 FROM SSISDB.catalog.folders WHERE name = N'$env:SSIS_DEST_FOLDER')
          BEGIN
              EXEC SSISDB.catalog.create_folder @folder_name = N'$env:SSIS_DEST_FOLDER';
          END

          DECLARE @project_stream VARBINARY(MAX) = CONVERT(VARBINARY(MAX), 0x$hexString, 1);
          EXEC SSISDB.catalog.deploy_project
              @folder_name = N'$env:SSIS_DEST_FOLDER',
              @project_name = N'$env:SSIS_PROJECTS_FOLDER',
              @project_stream = @project_stream;
          "@

          $tempSqlPath = "$env:RUNNER_TEMP\deploy_ssis_project.sql"
          [System.IO.File]::WriteAllText($tempSqlPath, $sql)

          & sqlcmd -S $env:SQL_SERVER_NAME -U $env:SQL_USERNAME -P $env:SQL_PASSWORD -d SSISDB -i $tempSqlPath -b

          if ($LASTEXITCODE -ne 0) {
              throw "SSIS project deployment failed with exit code $LASTEXITCODE"
          }
        env:
          SQL_SERVER_NAME: ${{ env.SQL_SERVER_NAME }}
          SQL_USERNAME: ${{ env.SQL_USERNAME }}  # LuckyManamela
          SQL_PASSWORD: ${{ env.SQL_PASSWORD }}  # Password for LuckyManamela
          SSIS_DEST_FOLDER: ${{ env.SSIS_DEST_FOLDER }}
          SSIS_PROJECTS_FOLDER: ${{ env.SSIS_PROJECTS_FOLDER }}
          SSIS_SOURCE_PATH: ${{ env.SSIS_SOURCE_PATH }}

      - name: Create SQL Agent Job if Missing
        shell: powershell
        run: |
          $packagePath = "/SSISDB/$env:SSIS_DEST_FOLDER/$env:SSIS_PROJECTS_FOLDER/$env:PACKAGE_NAME"
          $sql = @"
          USE msdb;
          IF NOT EXISTS (SELECT 1 FROM msdb.dbo.sysjobs WHERE name = N'$env:JOB_NAME')
          BEGIN
            DECLARE @jobId UNIQUEIDENTIFIER;
            EXEC msdb.dbo.sp_add_job
              @job_name = N'$env:JOB_NAME',
              @enabled = 1,
              @description = N'Data Migration SSIS Job',
              @start_step_id = 1,
              @owner_login_name = SUSER_SNAME(),
              @job_id = @jobId OUTPUT;

            EXEC msdb.dbo.sp_add_jobstep
              @job_id = @jobId,
              @step_id = 1,
              @step_name = N'RunMigrationStep',
              @subsystem = N'SSIS',
              @command = N'/ISSERVER \""$packagePath\"" /SERVER "$env:SQL_SERVER_NAME"',
              @database_name = N'master',
              @on_success_action = 1,
              @on_fail_action = 2;

            EXEC msdb.dbo.sp_add_jobserver @job_id = @jobId, @server_name = N'$env:SQL_SERVER_LOCAL';
          END
          "@
          & sqlcmd -S $env:SQL_SERVER_NAME -U $env:SQL_USERNAME -P $env:SQL_PASSWORD -Q $sql -b

      - name: Start SQL Agent Job
        shell: powershell
        run: |
          & sqlcmd -S $env:SQL_SERVER_NAME -U $env:SQL_USERNAME -P $env:SQL_PASSWORD -Q "EXEC msdb.dbo.sp_start_job @job_name = N'$env:JOB_NAME';" -b