name: Expose SQL Server with ngrok

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-and-expose-sql:
    runs-on: ubuntu-latest
    
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "LuckyManamela@$2000"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "exit 0"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Wait for SQL Server to be ready
        run: sleep 30

      - name: Run SQL script to set up DB and stored procedure
        run: |
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "LuckyManamela@$2000" -i setup.sql

      - name: Install dependencies (wget, unzip, jq)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip jq

      - name: Install ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          sudo mv ngrok /usr/local/bin

      - name: Start ngrok TCP tunnel on port 1433
        run: |
          # Start ngrok in the background
          nohup ngrok tcp 1433 --authtoken ${{ secrets.NGROK_AUTH_TOKEN }} --region=us > ngrok.log 2>&1 &
          
          # Wait a few seconds for ngrok to initialize
          sleep 5
          
          # Fetch tunnel info from ngrok's local API
          curl -s http://127.0.0.1:4040/api/tunnels > tunnels.json
          echo "tunnels.json output:"
          cat tunnels.json
          
          # Extract the public TCP URL (e.g. 'tcp://0.tcp.ngrok.io:12345')
          export NGROK_TCP_URL=$(jq -r '.tunnels[] | select(.proto=="tcp") | .public_url' tunnels.json)
          echo "NGROK_TCP_URL=$NGROK_TCP_URL"

          # Optionally, write the address to a file for reference in subsequent steps
          echo "$NGROK_TCP_URL" > tunnel-url.txt

      - name: Display the ngrok tunnel address
        run: |
          echo "Use the following connection string to reach SQL Server:"
          echo "Server=${NGROK_TCP_URL#tcp://};User ID=sa;Password=LuckyManamela@$2000;"

